name: ci

on:
  pull_request:
    branches: [main]

jobs:
  style:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.2"

      - name: Install pytest
        run: uv add pytest

      - name: Run tests
        run: |
          cd ./tests
          uv run pytest

      - name: Install Ruff
        run: uv add ruff

      - name: Check formatting and linting
        run: uv run ruff check .
